config/routes.rb
ReservationProject::Application.routes.draw do
  
  get "welcome/index"

  Rails.application.routes.draw do
  devise_for :users
    
    resources :reservations
    root 'welcome#index'
    end 

  

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservation_item_controller.rb
class ReservationItemController < ApplicationController
	def new
		
	end
	def create
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	def index
    @reservations = Reservation.all
  end
  	def show
    	@reservation = Reservation.find(params[:id])
  	end
	def new
	end
	def create
		@reservation = Reservation.new(reservation_params)
		@reservation.save
		redirect_to @reservation
	end  
	private 
	def reservation_params
	params.require(:reservation).permit(:pickup_location,:pickup_time,:dropoff_time)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservation_item_helper.rb
module ReservationItemHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReservationProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>

<%if current_user%>
	<%=current_user.email %> <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<%else %>
	<%= link_to 'Login', new_user_session_path %>
<%end%>

<%= yield %>

</body>
</html>

app/views/reservation_item/new.html.erb
<h1> New Reservation </h1>
<%= form_for :reservation_item do |f| %>
  <p>
    <%= f.label :Pickup_location %><br>
    <%= f.text_field :pickup_location %>
  </p>
 
  <p>
    <%= f.label :Pickup_Time %><br>
    <%= f.datetime_select :pickup_time %>
  </p>
  <p>
    <%= f.label :Dropoff_Time %><br>
    <%= f.datetime_select :dropoff_time %>
  </p> 
  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/reservations/index.html.erb
<h1>Listing Reservations</h1>
 
<table>
  <tr>
    <th>Location</th>
    <th>Pickup Time</th>
    <th>Dropoff Time</th>
  </tr>
 
  <%= @reservations.each do |reservation| %>
    <tr>
      <td><%= reservation.pickup_location %></td>
      <td><%= reservation.pickup_time %></td>
      <td><%= reservation.dropoff_time %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>
<%= form_for :reservation, url: reservations_path do |f| %>
  <p>
    <%= f.label :Pickup_location %><br>
    <%= f.text_field :pickup_location %>
  </p>
 
  <p>
    <%= f.label :Pickup_Time %><br>
    <%= f.datetime_select :pickup_time %>
  </p>
  <p>
    <%= f.label :Dropoff_Time %><br>
    <%= f.datetime_select :dropoff_time %>
  </p> 
  <p>
    <%= f.submit %>
  </p>
  
<% end %>
<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p>
	<strong>Pickup Location</strong>
	<%= if @reservation!=nil
		@reservation.pickup_location
		end %>
</p>
<p>
	<strong>Pickup Time</strong>
	<%= if @reservation!=nil
		@reservation.pickup_time
		end %>
</p>
<p>
	<strong>Dropoff Time</strong>
	<%= if @reservation!=nil
		@reservation.dropoff_time
		end %>
</p>
<%= link_to 'Back', reservations_path %>

app/views/welcome/index.html.erb
<h1>Reservation Portal</h1>
<%= link_to 'Reservation Portal', controller: 'reservations' %>